-- CreateTable
CREATE TABLE "Event" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "start" DATETIME NOT NULL,
    "end" DATETIME NOT NULL,
    "userId" INTEGER NOT NULL,
    "plantId" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Event_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER" ("user_id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Event_plantId_fkey" FOREIGN KEY ("plantId") REFERENCES "PLANT" ("plant_id") ON DELETE SET NULL ON UPDATE CASCADE
);
