name: CI Tests

on: [push, pull_request]

jobs:
  test:
    name: Run All Tests (Jest + Playwright)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Change to app directory
        working-directory: ./plant-care-assistant
        run: echo "Moved to project directory"

      - name: Install dependencies
        working-directory: ./plant-care-assistant
        run: npm install

      - name: Run unit tests
        working-directory: ./plant-care-assistant
        run: npm test:unit
