name: Playwright Tests
on:
  push:
    branches: 
      - dev
      - main
      - master
      - 'feature/**'
      - 'feature-*'
  pull_request:
    branches: 
      - dev
      - main
      - master
      - 'feature/**'
      - 'feature-*'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
  env:
    DATABASE_URL: postgresql://postgres:postgres@localhost:54322/postgres
    DIRECT_URL: postgresql://postgres:postgres@localhost:54322/postgres
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 23

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1

    - name: Start Supabase local
      working-directory: ./plant-care-assistant
      run: supabase start

    - name: Export local Supabase keys
      working-directory: ./plant-care-assistant
      run: |
       supabase status -o env | grep -E 'ANON_KEY|SERVICE_ROLE_KEY' >> $GITHUB_ENV
       echo "NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321" >> $GITHUB_ENV

    - name: Install dependencies
      working-directory: ./plant-care-assistant
      run: npm ci

    - name: Setup database
      working-directory: ./plant-care-assistant
      run: |
        npx prisma generate
        npx prisma db push
        npx prisma db seed

    - name: Create test user
      working-directory: ./plant-care-assistant
      run: |
        # Create test user via Supabase Auth API
        curl -X POST 'http://localhost:54321/auth/v1/signup' \
          -H "apikey: $NEXT_PUBLIC_SUPABASE_ANON_KEY" \
          -H "Content-Type: application/json" \
          -d '{"email": "bradley.loizeau@gmail.com", "password": "Password123", "email_confirm": true}' || echo "User might already exist"

    - name: Install Playwright Browsers
      working-directory: ./plant-care-assistant
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      working-directory: ./plant-care-assistant
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: plant-care-assistant/playwright-report/
        retention-days: 30
