name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      DIRECT_URL: ${{ secrets.TEST_DIRECT_URL }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.TEST_SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Debug environment variables
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL is set: ${{ secrets.TEST_SUPABASE_URL != '' }}"
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY is set: ${{ secrets.TEST_SUPABASE_ANON_KEY != '' }}"
          echo "DATABASE_URL is set: ${{ secrets.TEST_DATABASE_URL != '' }}"
          echo "DIRECT_URL is set: ${{ secrets.TEST_DIRECT_URL != '' }}"

      - name: Install dependencies
        working-directory: ./plant-care-assistant
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./plant-care-assistant
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./plant-care-assistant
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: plant-care-assistant/playwright-report/
          retention-days: 30
